### ISSUE TITLE
Check if version is actually latest

### ISSUE THREAD

**Issue by peter-svensson** [buildkite-plugins/buildkite-plugin-linter#512]
If the tags `v1` and `v1.0.1` actually target the same commit I get an error `Readme version numbers out of date. Latest is v1.0.1`
This is because `const tags = await git.listTags({ fs, dir: pluginPath })` have no concept of multiple tags being the "same" version.
Is this the intended behaviour?

Somewhat related to #485

**Comment by toote** [comment]
Hi @peter-svensson, the plugin does not look at what the actual tags point to, just the tags themselves. It assumes semantic versioning and uses [the compare-versions library](https://www.npmjs.com/package/compare-versions) to compare version numbers.

With that said, I believe the issue comes from the fact that `v1` and `v1.0.1` are not the same in semantic versioning, `v1` would be the same as `v1.0.0` (thus older that `v1.0.1`) and the library thinks the same:

```
> const compareVersions = require('compare-versions')
undefined
> compareVersions.compareVersions('v1', 'v1.0') // 0 means they are equal
0
> compareVersions.compareVersions('v1', 'v1.0.0') // 0 means they are equal
0
> compareVersions.compareVersions('v1', 'v1.0.1') // -1 means v1 < v1.0.1
-1
> compareVersions.compareVersions('v1.0', 'v1.0.1') // -1 means v1.0 < v1.0.1
-1
> compareVersions.compareVersions('v1.2', 'v2') // -1 means v1.2 < v2
-1
> compareVersions.compareVersions('v2.0', 'v1.0.1') // 1 means v2 > v1.0.1
1
```
